version: '3'
services:
    crawler:
        build:
            context: .
            dockerfile: DockerFile
        image: figure_crawler
        container_name: crawler
        env_file: .env/.env.dev
        volumes:
            - .:/app
        working_dir: /app
        stdin_open: true
        tty: true
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        container_name: db
        env_file: .env/.env.dev
        ports:
            - 5432:5432
        # volumes:
        #     - ./data:/var/lib/postgresql/data