version: '3'
services:
    crawler:
        env_file: .env/.env.dev
        build: .
        image: crawler
        container_name: crawler
        volumes:
            - .:/app
        stdin_open: true
        tty: true